# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "OpenDateRange"
version = "1.0.0"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=2.7.18"
classifiers = [
    "date", "time", "time range", "range", "date range", "date time"
]

[project.urls]
Homepage = "https://github.com/tlie03/OpenDateRange"